name: Caching npm packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: ['install']
    steps:
      - uses: actions/checkout@v3
      - name: Recover node modules
        uses: actions/cache@v3
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: ['install']
    steps:
      - uses: actions/checkout@v3
      - name: Recover node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Create cache for dist
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build project
        run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: ['lint', 'build']
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Recover node modules
        uses: actions/cache@v3
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Recover dist folder
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-dist-node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create release
        run: npx semantic-release

  deploy:
    runs-on: ubuntu-latest
    needs: ['lint', 'build']
    steps:
      - name: Call Render hook to deploy
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://api.render.com/deploy/srv-cdr7e4da4991vasrjdp0?key=aNDpQBBRm8E'
          method: 'GET'
